In [2]:
import torch
import numpy as np

In [3]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
nums = torch.arange(9)
nums

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
type(nums)

torch.Tensor

In [10]:
#토치 텐서 넘파이로 변환
nums.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [11]:
nums.reshape(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [14]:
randoms = torch.rand((3,3))
randoms

tensor([[0.6744, 0.3392, 0.1309],
        [0.9499, 0.1423, 0.3932],
        [0.2067, 0.2349, 0.3341]])

In [15]:
zeross = torch.zeros((4,4))
zeross

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
oness = torch.ones((5,5))
oness

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [18]:
torch.zeros_like(oness)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

# pytorch Operations 

In [19]:
nums *3

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [21]:
nums = nums.reshape((3,3))
nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [22]:
nums +nums

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [23]:
torch.add(nums, 3)

tensor([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [25]:
result = torch.add(nums, 3)
result

tensor([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [26]:
result.numpy()

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int64)

# View 

In [28]:
range_nums = torch.arange(9).reshape(3,3)
range_nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [29]:
# view는 reshape와 다를게 없고 reshape를 권장함 
range_nums.view(-1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
range_nums.view(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

# Slice and Index 

In [36]:
nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [37]:
nums[1]

tensor([3, 4, 5])

In [38]:
nums[1,1]

tensor(4)

In [39]:
nums[:2, 1:]

tensor([[1, 2],
        [4, 5]])

In [40]:
nums[1:]

tensor([[3, 4, 5],
        [6, 7, 8]])

# Complie 
numpy를 torch tensor로 불러오기

In [41]:
arr = np.array([1,2,2])

In [42]:
arr_torch = torch.from_numpy(arr)
arr_torch

tensor([1, 2, 2], dtype=torch.int32)

In [43]:
arr_torch.float()

tensor([1., 2., 2.])

In [44]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [45]:
arr_torch.to(device)

tensor([1, 2, 2], device='cuda:0', dtype=torch.int32)

# AutoGrad
기울기를 줘서 학습이 되게 하는 것

In [56]:
x = torch.ones(2,2,requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [57]:
y = x+2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [58]:
print(y.grad_fn)

In [59]:
z = y * y *3

In [60]:
out = z.mean()
out

tensor(27., grad_fn=<MeanBackward0>)

In [61]:
out.backward()
print(x.grad) #x의 기울기

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [62]:
print(x.requires_grad)
print((x**2).requires_grad)

True
True


In [63]:
with torch.no_grad():
    print((x**2).requires_grad)

False


# PyTorch Data Preprocess 

In [64]:
import torch
from torchvision import datasets, transforms

## Data Loader 부르기
파이토치는 DataLoader를 불러 model에 넣음 

In [65]:
batch_size = 32
test_batch_size = 32

In [73]:
train_loader = torch.utils.data.DataLoader(datasets.MNIST('dataset/', train = True, download = True, transform = transforms.Compose([
transforms.ToTensor(), transforms.Normalize(mean=(0.5,), std=(0.5))])), 
                                          batch_size=batch_size, shuffle=True)

0it [00:00, ?it/s]

Extracting dataset/MNIST\raw\train-images-idx3-ubyte.gz to dataset/MNIST\raw


0it [00:00, ?it/s]

Extracting dataset/MNIST\raw\train-labels-idx1-ubyte.gz to dataset/MNIST\raw


0it [00:00, ?it/s]

Extracting dataset/MNIST\raw\t10k-images-idx3-ubyte.gz to dataset/MNIST\raw


0it [00:00, ?it/s]

Extracting dataset/MNIST\raw\t10k-labels-idx1-ubyte.gz to dataset/MNIST\raw
Processing...
Done!


In [74]:
test_loader = torch.utils.data.DataLoader( datasets.MNIST('dataset/', train=False, transform = transforms.Compose([
    transforms.ToTensor(), transforms.Normalize((0.5,),(0.5))]))
                                         , batch_size = test_batch_size, shuffle=True)

In [75]:
images, labels = next(iter(train_loader))

In [76]:
images.shape

torch.Size([32, 1, 28, 28])

In [77]:
labels.shape

torch.Size([32])

## 데이터 시각화 